{% set name = "yesqa" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/yesqa-{{ version }}.tar.gz
  sha256: 209c17274f3c0cc22195ddb26f93df3523634d0756f756913ed05cba970efad9

build:
  entry_points:
    - yesqa = yesqa:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - flake8 >=3.9
    - tokenize-rt >=2.1

test:
  imports:
    - yesqa
  commands:
    - pip check
    - yesqa --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/asottile/yesqa
  summary: Automatically remove unnecessary `# noqa` comments.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fuglede
